language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mradman/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mradman/react-test npm test

after_success:
  - docker build -t mradman/multi-client ./client
  - docker build -t mradman/multi-nginx ./nginx
  - docker build -t mradman/multi-server ./server
  - docker build -t mradman/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Tale those images and push them to docker hub
  - docker push mradman/multi-client
  - docker push mradman/multi-nginx
  - docker push mradman/multi-server
  - docker push mradman/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-976230332130"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
